language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"

channels:
- conda-forge
- defaults

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION asgiref=3.2.5 ca-certificates=2020.1.1 certifi=2019.11.28 django=3.0.3 libcxx=9.0.1 libffi=3.2.1 ncurses=6.1 openssl=1.1.1f pip=20.0.2 python=3.8.2 python_abi=3.8 pytz=2019.3 readline=8.0 setuptools=46.1.3 sqlite=3.30.1 sqlparse=0.3.0 tk=8.6.10 wheel=0.34.2 xz=5.2.4 zlib=1.2.11
  - conda activate test-environment
  - python setup.py install

script:
  - python manage.py test
  # Your test script goes here
