language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"

env:
  - SECRET_KEY='TEST'

services:
  - sqlite

install:
  - sudo apt-get update
  - pipenv install

script:
  - python manage.py test
